# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/mqtt_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/mqtt_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/mqtt_data.proto\x12\tmqtt_data\"\xac\x01\n\nFieldValue\x12\x12\n\nfield_name\x18\x01 \x01(\t\x12\x16\n\x0cstring_value\x18\x02 \x01(\tH\x00\x12\x13\n\tint_value\x18\x03 \x01(\x03H\x00\x12\x15\n\x0b\x66loat_value\x18\x04 \x01(\x01H\x00\x12\x14\n\nbool_value\x18\x05 \x01(\x08H\x00\x12\x14\n\njson_value\x18\x06 \x01(\x0cH\x00\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\x42\x07\n\x05value\"\xd1\x01\n\nDetailData\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12%\n\x06\x66ields\x18\x04 \x03(\x0b\x32\x15.mqtt_data.FieldValue\x12\x35\n\x08metadata\x18\x05 \x03(\x0b\x32#.mqtt_data.DetailData.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"`\n\x0c\x46ieldMapping\x12\x12\n\nmqtt_field\x18\x01 \x01(\t\x12\x11\n\tdb_column\x18\x02 \x01(\t\x12\x11\n\tdata_type\x18\x03 \x01(\t\x12\x16\n\x0esave_to_detail\x18\x04 \x01(\x08\"u\n\rMappingConfig\x12\x12\n\ntopic_name\x18\x01 \x01(\t\x12\x14\n\x0ctarget_table\x18\x02 \x01(\t\x12)\n\x08mappings\x18\x03 \x03(\x0b\x32\x17.mqtt_data.FieldMapping\x12\x0f\n\x07version\x18\x04 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.mqtt_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETAILDATA_METADATAENTRY']._loaded_options = None
  _globals['_DETAILDATA_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_FIELDVALUE']._serialized_start=37
  _globals['_FIELDVALUE']._serialized_end=209
  _globals['_DETAILDATA']._serialized_start=212
  _globals['_DETAILDATA']._serialized_end=421
  _globals['_DETAILDATA_METADATAENTRY']._serialized_start=374
  _globals['_DETAILDATA_METADATAENTRY']._serialized_end=421
  _globals['_FIELDMAPPING']._serialized_start=423
  _globals['_FIELDMAPPING']._serialized_end=519
  _globals['_MAPPINGCONFIG']._serialized_start=521
  _globals['_MAPPINGCONFIG']._serialized_end=638
# @@protoc_insertion_point(module_scope)
